### ISSUE TITLE
kcc cannot compile iotivity

### ISSUE THREAD

**Issue by shijieg2** [kframework/c-semantics#322] opened 2018-10-04 11:49 UTC
You can reproduce the problem like this:
```
# start from an Ubuntu 16.04 VM
#install java
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer

#Install kcc: version 1.0 GNU-compatibleBuild number: #c9eaccf-1537409156414
wget https://runtimeverification.com/match/1.0/rv-match-linux-64-1.0-SNAPSHOT.jar
sudo java -jar rv-match-linux-64-1.0-SNAPSHOT.jar

# Install build env for iotivity:
sudo apt-get install \
    build-essential git scons libtool autoconf \
    valgrind doxygen wget unzip chrpath
# Install development support for external libraries:
sudo apt-get install \
    libboost-dev libboost-program-options-dev libboost-thread-dev \
    uuid-dev libexpat1-dev libglib2.0-dev libsqlite3-dev libcurl4-gnutls-dev

# clone the repository from github. shijieg2 be my github username.
git clone https://github.com/shijieg2/iotivity.git
cd iotivity

# modify build_common/SConsript set compiler & environment variable
sed -i 's/gcc/kcc/g' build_common/SConscript
# specify the environment variables in scons script.
sed "/^    env = Environment(/a\        CC='kcc',\n        ENV = {'PATH': os.environ['PATH'],\n               'HOME': os.environ['HOME']}," -i build_common/SConscript

#get dependencies
git clone https://github.com/intel/tinycbor.git extlibs/tinycbor/tinycbor -b v0.5.1
git clone https://github.com/ARMmbed/mbedtls.git extlibs/mbedtls/mbedtls -b mbedtls-2.4.2

#run scons
scons
```

**Comment by chathhorn** [comment] 2018-10-09 14:39
Hi, thanks a lot for the bug report!

Could you include some output from the build (or other symptoms) so I know when I'm reproducing the issue you're seeing?

**Comment by chathhorn** [comment] 2018-11-06 20:03
Closing because I assume the other iotivity issue subsumes this one.

**Closed by chathhorn** 2018-11-06 20:03 UTC
